# Automatically generated by configure - do not modify
# Configured with: './configure'
prefix=/usr
includedir=/usr/include
libdir=/usr/lib
libdevdir=/usr/lib
relativelibdir=
mandir=/usr/man
datadir=/usr/share
CONFIG_NOLIBC=y
CONFIG_HAVE_KERNEL_RWF_T=y
CONFIG_HAVE_KERNEL_TIMESPEC=y
CONFIG_HAVE_OPEN_HOW=y
CONFIG_HAVE_STATX=y
CONFIG_HAVE_GLIBC_STATX=y
CONFIG_HAVE_CXX=y
CONFIG_HAVE_UCONTEXT=y
CONFIG_HAVE_STRINGOP_OVERFLOW=y
CONFIG_HAVE_ARRAY_BOUNDS=y
CONFIG_HAVE_FANOTIFY=y
CC=gcc
CXX=g++
